### ISSUE TITLE
Download app

### ISSUE THREAD

**Issue by xmha97** [davidp799/patco-today#4]
Hi, how can I download this app?

**Comment by davidp799** [comment]
Hi, the app is still in development. To download a debug version, visit the Actions tab, select a workflow run, and scroll down to the artifacts section to download "app-debug.apk".

**Comment by davidp799** [comment]
Hi, the app is still in development. To download a debug version, visit the Actions tab, select a workflow run, and scroll down to the artifacts section to download "app-debug.apk".

**Comment by xmha97** [comment]
Thanks 🙏
