### ISSUE TITLE
Add monochrome icon 

### ISSUE THREAD

**Issue by xmha97** [davidp799/patco-today#5]
Please support the Android 13 "Themed App Icons" feature.

![Screenshot_2023-04-06-02-42-15-970_de mm20 launcher2 release](https://user-images.githubusercontent.com/23485114/230232130-cd45a670-3535-47ea-ad12-34a232e71f5d.jpg)

**Comment by davidp799** [comment]
Just implemented it in the latest commit! Download the latest app-debug.apk to check it out :)

**Comment by xmha97** [comment]
Thanks. 🙏
